@endpoint=http://localhost:3000/api

### PRODUCT ###

GET {{endpoint}}/products

###

GET {{endpoint}}/products/?id=66f756cf3f64ead112967bbc

###

POST {{endpoint}}/products
Content-Type: application/json

{
  "title": "string",
  "price": 12,
  "image": "string",
  "description": "string"
}

###

PUT {{endpoint}}/products/66f743678b4ebe8cb745c59a
Content-Type: application/json

{
  "title": "number",
  "price": 11,
  "image": "number",
  "description": "number"
}

###

DELETE {{endpoint}}/products/66f739fd88022011fa3ff602

###
PATCH {{endpoint}}/products/66f743678b4ebe8cb745c59a
# Could return 405 Method Not Allowed

### TAG ###

GET {{endpoint}}/tags

###
POST {{endpoint}}/tags
# Could return 405 Method Not Allowed

###
POST {{endpoint}}/tags/66f743678b4ebe8cb745c59a
# Could return 405 Method Not Allowed

### CATEGORY ###

GET {{endpoint}}/categories

###
POST {{endpoint}}/categories
# Could return 405 Method Not Allowed

###
POST {{endpoint}}/categories/66f7661cdcde0ab612892b5c
# Could return 405 Method Not Allowed

### USER ###

GET {{endpoint}}/user
Content-Type: application/json
  
  {
    "email": "fake.user@email.com",
    "password": "azerty"
  }

###

POST {{endpoint}}/user
Content-Type: application/json

{
  "firstname": "fake",
  "lastname": "user",
  "email": "fake.user@email.com",
  "password": "azerty"
}

###

DELETE {{endpoint}}/user
Content-Type: application/json
  
  {
    "email": "fake.user@email.com",
    "password": "qwerty"
  }