services:
  api:
    container_name: omazon-api
    build:
      context: .
      dockerfile: ./src/Dockerfile.api
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DB_URI=${DB_URI}
    networks:
      - omazon-network
    depends_on:
      - mongo-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo-db:
    image: mongo:latest
    container_name: omazon-mongo
    ports:
      - "27017:27017"
    restart: always
    environment: 
      MONGO_INITDB_DATABASE: omazon-db
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
      - ./init-database.js:/docker-entrypoint-initdb.d/init-database.js:ro
      - mongo-data:/data/db
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    networks:
      - omazon-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  omazon-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local